// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: first_service_pb.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirstServicePbClient is the client API for FirstServicePb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstServicePbClient interface {
	Add(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type firstServicePbClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstServicePbClient(cc grpc.ClientConnInterface) FirstServicePbClient {
	return &firstServicePbClient{cc}
}

func (c *firstServicePbClient) Add(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/api.first_service_pb/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstServicePbServer is the server API for FirstServicePb service.
// All implementations must embed UnimplementedFirstServicePbServer
// for forward compatibility
type FirstServicePbServer interface {
	Add(context.Context, *RequestMessage) (*ResponseMessage, error)
	mustEmbedUnimplementedFirstServicePbServer()
}

// UnimplementedFirstServicePbServer must be embedded to have forward compatible implementations.
type UnimplementedFirstServicePbServer struct {
}

func (UnimplementedFirstServicePbServer) Add(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedFirstServicePbServer) mustEmbedUnimplementedFirstServicePbServer() {}

// UnsafeFirstServicePbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstServicePbServer will
// result in compilation errors.
type UnsafeFirstServicePbServer interface {
	mustEmbedUnimplementedFirstServicePbServer()
}

func RegisterFirstServicePbServer(s grpc.ServiceRegistrar, srv FirstServicePbServer) {
	s.RegisterService(&FirstServicePb_ServiceDesc, srv)
}

func _FirstServicePb_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServicePbServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.first_service_pb/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServicePbServer).Add(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// FirstServicePb_ServiceDesc is the grpc.ServiceDesc for FirstServicePb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirstServicePb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.first_service_pb",
	HandlerType: (*FirstServicePbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _FirstServicePb_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "first_service_pb.proto",
}
